= ¿En qué creo?

[quote,attribution,citation title and information]
Creo en un Dios Todopoderoso, cuyo nombre es Jehová, que envió a su hijo Jesucristo para redimir los pecados del hombre, a través de la fe, al creer que Dios le resucitó de los muertos, para ser Señor de todo lo que existe por los Siglos de los Siglos, Amén.

[quote,attribution,citation title and information]
Creo en el arrepentimiento y la conversión de los malos caminos, quien hace lo malo puede dejar eso atrás y tratar de comenzar una vida nueva.

[quote,attribution,citation title and information]
Creo que el trabajo duro y la disciplina son un testimonio de nuestras convicciones, que para lograr las metas hay que accionar firmemente, y que todo lo demás sucederá conforme a esas convicciones

[quote,attribution,citation title and information]
El ser humano es la especie creada y facultada para cuidar y proteger a otros seres vivos, al ambiente y al conocimiento.

[quote,attribution,citation title and information]
Creo firmemente que ningún hombre es más grande que otro hombre, lo que nos diferencia parte de la pura voluntad de crecer, crear y persistir.

[quote,anónimo]
Hay más honor en la derrota que en el potencial desperdiciado